"""CPU-only tests for the OpenAI-standard message-dict trace SDPO_ReAct records
and dumps for native (multi_turn.generate) tool-calling rollout.

Two examples, matching how the ecosystem (e.g. i-DeepSearch observation-masking
eval logs) represents multi-turn tool-calling trajectories:

  1. A message list in the standard schema -- assistant turns carry a structured
     `tool_calls` field (id / type / function{name, arguments}), tool turns carry
     `tool_call_id` -- renders correctly through Qwen3's OWN chat template
     (tools=all_tool_specs), producing the native <tools> block, `<tool_call>`
     assistant turns, and `<tool_response>` observation turns, and tokenizes
     without error. Confirms the recorded dict is re-sendable, not lossy text.

  2. sdpo_react._reconstruct_messages turns a sample (baked-in chat-templated
     prompt + the live metadata["messages"] the rollout recorded) into that same
     OpenAI-standard message list: a clean system + user split, then the
     assistant(+tool_calls)/tool(+tool_call_id) turns verbatim.

No GPU, no Docker, no network beyond the one-time HF tokenizer download shared
with the sibling tests.
"""

import json

import pytest
from tests.ci.ci_register import register_cpu_ci

from examples.SRD.sdpo_react import _reconstruct_messages
from examples.SRD.tools.registry import MINIMAL_SYSTEM_PROMPT, all_tool_specs
from miles.utils.types import Sample

register_cpu_ci(est_time=30, suite="stage-b-cpu", labels=[])

# qwen25/qwen3 share the <tool_call> grammar; the 0.5B instruct tokenizer carries
# a tool-aware chat template and is the qwen tool-call parser's reference family.
MODEL_NAME = "Qwen/Qwen2.5-0.5B-Instruct"

# ---------------------------------------------------------------------------
# The EXACT string _standard_conversation() renders to via the qwen chat
# template (tokenize=False), captured verbatim so you can eyeball the "before
# tokenize" template here without running anything. Note:
#   * the "# Tools ... <tools>...</tools> ... For each function call ..." block
#     is AUTO-GENERATED by the template from tools=all_tool_specs (NOT injected
#     by us);
#   * assistant tool calls render as <tool_call>{...}</tool_call>;
#   * tool observations render as a `user` turn wrapping <tool_response>...;
#   * the user question separator is just the ChatML "<|im_start|>user\n" marker
#     -- no "Question:" label is added or needed.
# "after tokenize" is the token-id list of THIS SAME string; the test asserts
# tok.decode(input_ids) == this string (round-trips exactly, 616 tokens on the
# 0.5B tokenizer).
# ---------------------------------------------------------------------------
EXPECTED_RENDERED = (
    "<|im_start|>system\n"
    "You solve the user's problem. You have tools available (declared below); call any that help, as many times as you need. Multiple tool calls in one turn run concurrently. When done, give your final answer inside <answer> and </answer> tags, e.g. <answer>42</answer>. Put ONLY the final answer inside the tags.\n"
    "\n"
    "# Tools\n"
    "\n"
    "You may call one or more functions to assist with the user query.\n"
    "\n"
    "You are provided with function signatures within <tools></tools> XML tags:\n"
    "<tools>\n"
    '{"type": "function", "function": {"name": "code_interpreter", "description": "Execute Python code in an isolated sandbox and return its stdout. Use this for calculations, symbolic math (sympy), or verifying a numeric answer before giving your final answer. The sandbox has sympy, numpy, and scipy preinstalled; it has no network access.", "parameters": {"type": "object", "properties": {"code": {"type": "string", "description": "Raw Python source code to execute -- NOT wrapped in a markdown code fence. Do NOT include ```python or ``` markers; pass only the executable code itself. Print anything you want to see."}}, "required": ["code"]}}}\n'
    '{"type": "function", "function": {"name": "cli_exec", "description": "Run a shell command in the sandbox and return its combined stdout/stderr. Use for file/OS-level tasks (ls, cat, grep, running a script). Runs in the same isolated container as code_interpreter; no network access.", "parameters": {"type": "object", "properties": {"command": {"type": "string", "description": "Shell command to run, e.g. \\"ls -la && cat foo.py\\"."}}, "required": ["command"]}}}\n'
    '{"type": "function", "function": {"name": "web_search", "description": "Search a local Wikipedia knowledge base and return the top passages for a query. Use for multi-hop factual questions: search for one fact, read the passages, then search again for the next hop. Returns titled passages, not a live web page.", "parameters": {"type": "object", "properties": {"query": {"type": "string", "description": "A focused search query (one hop / one fact at a time)."}}, "required": ["query"]}}}\n'
    "</tools>\n"
    "\n"
    "For each function call, return a json object with function name and arguments within <tool_call></tool_call> XML tags:\n"
    "<tool_call>\n"
    '{"name": <function-name>, "arguments": <args-json-object>}\n'
    "</tool_call><|im_end|>\n"
    "<|im_start|>user\n"
    "Which magazine started first, Arthur's Magazine or First for Women?<|im_end|>\n"
    "<|im_start|>assistant\n"
    "I should look up each founding date.\n"
    "<tool_call>\n"
    '{"name": "web_search", "arguments": "{\\"query\\": \\"Arthur\'s Magazine founded\\"}"}\n'
    "</tool_call><|im_end|>\n"
    "<|im_start|>user\n"
    "<tool_response>\n"
    "[doc 1] Arthur's Magazine was first published in 1844.\n"
    "</tool_response><|im_end|>\n"
    "<|im_start|>assistant\n"
    "<answer>Arthur's Magazine</answer><|im_end|>\n"
)


def _standard_conversation() -> list[dict]:
    """A realistic 2-hop search conversation in the OpenAI-standard schema that
    multi_turn.generate now records: assistant.tool_calls + tool.tool_call_id."""
    return [
        {"role": "system", "content": MINIMAL_SYSTEM_PROMPT},
        {"role": "user", "content": "Which magazine started first, Arthur's Magazine or First for Women?"},
        {
            "role": "assistant",
            "content": "I should look up each founding date.",
            "tool_calls": [
                {
                    "id": "call_0001",
                    "type": "function",
                    "function": {"name": "web_search", "arguments": json.dumps({"query": "Arthur's Magazine founded"})},
                }
            ],
        },
        {
            "role": "tool",
            "tool_call_id": "call_0001",
            "name": "web_search",
            "content": "[doc 1] Arthur's Magazine was first published in 1844.",
        },
        {"role": "assistant", "content": "<answer>Arthur's Magazine</answer>"},
    ]


class TestMessageDictRendersThroughQwenTemplate:
    """Example 1: the standard message dict -> Qwen chat template round-trip."""

    @pytest.fixture(scope="class")
    def tokenizer(self):
        from miles.utils.processing_utils import load_tokenizer

        return load_tokenizer(MODEL_NAME, trust_remote_code=True)

    def test_standard_dict_renders_and_tokenizes(self, tokenizer):
        messages = _standard_conversation()

        # ---- BEFORE tokenize: the full chat-template string -------------------
        rendered = tokenizer.apply_chat_template(
            messages, tools=all_tool_specs, tokenize=False, add_generation_prompt=False
        )
        # Print so `pytest -s` shows the exact "before tokenize" template.
        print("\n===== BEFORE TOKENIZE (rendered chat-template string) =====")
        print(rendered)
        print("===== END BEFORE =====")

        # Exact-match the captured template (see EXPECTED_RENDERED above) so any
        # drift in the rendered string is caught and visible in the diff.
        assert rendered == EXPECTED_RENDERED

        # Native tool block is auto-generated by the template from tools=..., not
        # hand-written; assistant tool_calls -> <tool_call>, tool turn ->
        # <tool_response>; the user separator is just "<|im_start|>user\n".
        assert "<tools>" in rendered
        assert "Arthur's Magazine founded" in rendered  # the structured arguments
        assert "<tool_response>" in rendered
        assert "<|im_start|>user\nWhich magazine started first" in rendered

        # ---- AFTER tokenize: token ids, and the detokenized string ------------
        # apply_chat_template(tokenize=True) returns a BatchEncoding; read
        # input_ids for the real token count (len() on it counts its 2 keys).
        enc = tokenizer.apply_chat_template(
            messages, tools=all_tool_specs, tokenize=True, add_generation_prompt=False
        )
        input_ids = enc["input_ids"] if hasattr(enc, "keys") else enc
        decoded = tokenizer.decode(input_ids)
        print("\n===== AFTER TOKENIZE =====")
        print(f"num tokens: {len(input_ids)}")
        print(f"first 20 input_ids: {input_ids[:20]}")
        print("----- detokenized string (tok.decode(input_ids)) -----")
        print(decoded)
        print("===== END AFTER =====")

        assert len(input_ids) > 50
        # tokenize -> detokenize round-trips EXACTLY back to the rendered string:
        # no lossy loss of the tool_call / tool_response structure.
        assert decoded == rendered == EXPECTED_RENDERED


class TestReconstructMessagesStandardSchema:
    """Example 2: _reconstruct_messages -> OpenAI-standard message list."""

    def test_native_live_messages_become_standard_schema(self):
        # Baked-in chat-templated prompt (system carries the <tools> block, then
        # the user question, then the assistant generation-prompt scaffold).
        prompt = (
            "<|im_start|>system\n" + MINIMAL_SYSTEM_PROMPT + "\n<tools>...</tools><|im_end|>\n"
            "<|im_start|>user\nWho wrote Hamlet?<|im_end|>\n"
            "<|im_start|>assistant\n<think>\n\n</think>\n\n"
        )
        # What multi_turn.generate records live on metadata["messages"].
        live = [
            {
                "role": "assistant",
                "content": "Let me search.",
                "tool_calls": [
                    {
                        "id": "call_ab",
                        "type": "function",
                        "function": {"name": "web_search", "arguments": json.dumps({"query": "Hamlet author"})},
                    }
                ],
            },
            {"role": "tool", "tool_call_id": "call_ab", "name": "web_search", "content": "[doc1] Shakespeare wrote it"},
            {"role": "assistant", "content": "<answer>Shakespeare</answer>"},
        ]
        sample = Sample(prompt=prompt, response="", metadata={"messages": live})

        messages = _reconstruct_messages(sample)

        # Clean system + user split from the prompt (no ChatML control tokens, no
        # empty generation-prompt scaffold), then the live turns verbatim.
        assert [m["role"] for m in messages] == ["system", "user", "assistant", "tool", "assistant"]
        assert messages[0]["content"].startswith("You solve the user's problem")
        assert messages[1]["content"] == "Who wrote Hamlet?"
        assert "<|im_start|>" not in messages[0]["content"]
        assert "<|im_end|>" not in messages[1]["content"]

        # Assistant turn keeps the STRUCTURED tool_calls field (not raw XML text).
        call = messages[2]["tool_calls"][0]
        assert "<tool_call>" not in messages[2]["content"]
        assert call["type"] == "function"
        assert call["function"]["name"] == "web_search"
        json.loads(call["function"]["arguments"])  # valid JSON arguments

        # Tool turn is linked back to the call by tool_call_id.
        assert messages[3]["role"] == "tool"
        assert messages[3]["tool_call_id"] == call["id"]

        # Final answer turn preserved.
        assert messages[-1]["content"] == "<answer>Shakespeare</answer>"

    def test_fallback_to_single_assistant_turn_when_no_live_record(self):
        # No metadata["messages"]/["turns"] (e.g. truncated before the loop
        # recorded anything) -> prompt split + raw response as one assistant turn.
        prompt = "<|im_start|>user\n2+2?<|im_end|>\n"
        sample = Sample(prompt=prompt, response="It is 4.", metadata={})
        messages = _reconstruct_messages(sample)
        assert messages == [
            {"role": "user", "content": "2+2?"},
            {"role": "assistant", "content": "It is 4."},
        ]
