"""
Utils to handle tool calls.
"""

import asyncio
import json
import uuid
from collections.abc import Callable
from typing import Any

import numpy as np
from openai.types.chat import ChatCompletionMessageToolCall
from pydantic import TypeAdapter
from sglang.srt.entrypoints.openai.protocol import Tool
from sglang.srt.function_call.core_types import ToolCallItem
from sglang.srt.function_call.function_call_parser import FunctionCallParser

from miles.utils.types import Sample

_DUMMY_USER = {"role": "user", "content": "dummy"}


def create_tool_call_parser(tool_specs, tool_call_parser):
    return FunctionCallParser(
        tools=TypeAdapter(list[Tool]).validate_python(tool_specs),
        tool_call_parser=tool_call_parser,
    )


async def execute_tool_calls(
    tool_calls: list[ToolCallItem | ChatCompletionMessageToolCall],
    execute_one: Callable,
) -> list[dict[str, Any]]:
    # Concurrent: when a single assistant turn emits MULTIPLE tool calls (e.g. a
    # multitool run firing web_search + code_interpreter together), run them at
    # once via gather rather than serially awaiting each -- the observations are
    # independent, so wall-clock = slowest single call, not the sum. Order is
    # preserved (gather returns in input order) so the tool-response tokens are
    # appended in the same order the model emitted the calls.
    return await asyncio.gather(*(_execute_tool_call(call, execute_one) for call in tool_calls))


async def _execute_tool_call(
    call: ToolCallItem | ChatCompletionMessageToolCall, execute_one: Callable
) -> dict[str, Any]:
    if isinstance(call, ChatCompletionMessageToolCall):
        name = call.function.name
        params = json.loads(call.function.arguments) if call.function.arguments else {}
        tool_call_id = call.id
    elif isinstance(call, ToolCallItem):
        name = call.name
        params = json.loads(call.parameters) if call.parameters else {}
        tool_call_id = f"call_{uuid.uuid4().hex[:24]}"
    else:
        raise TypeError(f"Unsupported tool call type: {type(call)}")

    result = await execute_one(name, params)
    assert isinstance(result, str)

    return {"role": "tool", "tool_call_id": tool_call_id, "content": result, "name": name}


def update_sample_with_tool_responses(sample: Sample, tool_messages: list[dict[str, Any]], tokenizer, chat_template_kwargs: dict | None = None):
    next_obs_tokens_ids: list[int] = tokenize_tool_responses(
        tool_messages, tokenizer=tokenizer, chat_template_kwargs=chat_template_kwargs
    )
    sample.response += tokenizer.decode(next_obs_tokens_ids)
    sample.response_length += len(next_obs_tokens_ids)
    sample.tokens += next_obs_tokens_ids
    sample.loss_mask += [0] * len(next_obs_tokens_ids)
    sample.rollout_log_probs += [0.0] * len(next_obs_tokens_ids)
    # !!! IMPORTANT R3 multi-turn fix !!! -- do NOT remove. Without this, any
    # MoE run with --use-rollout-routing-replay on a MULTI-TURN tool-calling
    # rollout HARD-CRASHES at the first train step (replay_data.py:79 shape
    # assert: routed_experts vs tokens off by the trailing tool-response length).
    # R3 rollout-routing-replay (MoE) multi-turn fix: tool-response tokens are
    # INSERTED into the trajectory, not generated by the model, so the rollout
    # engine returns no routed-expert (or indexer-topk) record for them. Pad the
    # per-token replay tensors with one all -1 row per tool-response token so the
    # tensor stays aligned with sample.tokens (the training-side consumer asserts
    # routed_experts.shape[0] == len(tokens) - 1; see replay_data.py). A row of
    # all -1 is the "no forced routing" sentinel replay_base._get_replay_result
    # already handles (falls back to free routing), which is correct here since
    # these positions are loss_mask=0. The NEXT generation turn re-prefills the
    # whole context and OVERWRITES rollout_routed_experts with the full-sequence
    # buffer (see update_sample_from_response), so this padding only ultimately
    # survives for a trailing tool response with no subsequent generation -- the
    # exact case that otherwise leaves the tensor short and crashes training.
    n_obs = len(next_obs_tokens_ids)
    if n_obs > 0:
        for attr in ("rollout_routed_experts", "rollout_indexer_topk"):
            arr = getattr(sample, attr, None)
            if arr is not None:
                pad = np.full((n_obs, *arr.shape[1:]), -1, dtype=arr.dtype)
                setattr(sample, attr, np.concatenate([arr, pad], axis=0))


# TODO: very naive implementation, need the to-be-implemented e2e test to validate.
def tokenize_tool_responses(
    tool_messages: list[dict[str, Any]],
    tokenizer,
    chat_template_kwargs: dict | None = None,
) -> list[int]:
    return _tokenize_postfix_messages(tool_messages, tokenizer, chat_template_kwargs=chat_template_kwargs)


def _tokenize_postfix_messages(
    postfix_messages: list[dict[str, Any]],
    tokenizer,
    chat_template_kwargs: dict | None = None,
) -> list[int]:
    dummy_assistant = _build_dummy_assistant(postfix_messages)
    base_messages = [_DUMMY_USER, dummy_assistant]

    messages_without = base_messages
    messages_with = base_messages + postfix_messages

    # Forward the run's chat-template kwargs (e.g. {"enable_thinking": False}) so
    # the NEXT assistant turn's generation prompt matches the FIRST turn. Without
    # this, a no-thinking run's initial prompt gets the "<think>\n\n</think>"
    # no-think marker (baked at data-prep) but every POST-tool-response turn is
    # re-templated here WITHOUT it, so the model reopens <think> and reasons
    # freely after the first tool call -- observed as populated <think> blocks
    # (4k+ chars) in a supposedly no-think run.
    ctk = chat_template_kwargs or {}
    tokens_with = tokenizer.apply_chat_template(
        messages_with, tokenize=True, add_generation_prompt=True, return_dict=False, **ctk
    )
    tokens_without = tokenizer.apply_chat_template(
        messages_without, tokenize=True, add_generation_prompt=False, return_dict=False, **ctk
    )

    assert tokens_with[: len(tokens_without)] == tokens_without, (
        f"Fail to tokenize_tool_responses caused by token prefix mismatch. "
        f"This can happen for thinking model or models with special chat template, "
        f"and this simple example does not support it yet, "
        f"since this means we cannot have a append-only token id list. "
        f"{tokens_with=} {tokens_without=} "
        f"{tokenizer.decode(tokens_with)=} {tokenizer.decode(tokens_without)=} "
    )
    return tokens_with[len(tokens_without) :]


def _build_dummy_assistant(tool_responses: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "role": "assistant",
        "content": "",
        "reasoning_content": " ",
        "tool_calls": [
            {
                "id": resp.get("tool_call_id", f"call0000{i}"),
                "type": "function",
                "function": {
                    "name": resp.get("name", "dummy_func"),
                    "arguments": {},
                },
            }
            for i, resp in enumerate(tool_responses)
        ],
    }
