"""Prompt-text suffixes for the code domain (build_code_data.py).

Each is appended to MINIMAL_SYSTEM_PROMPT there; kept as pure text here."""
CODE_SYSTEM_PROMPT_SUFFIX = (
    "\n\nFor programming problems, your solution is graded by running the LAST "
        "program you pass to code_interpreter (reading input from stdin, printing to "
        "stdout) against hidden test cases -- code you only write in text but never "
        "run does not count. Break the problem into steps, and before submitting, "
        "VERIFY your program by running it through code_interpreter with a sample "
        "input passed via the `stdin` parameter -- never hardcode a fake stdin "
        "inside the code, since the same code is re-run against the real hidden "
        "input at grading time and a hardcoded override would replace it."
    + "\n\nExample:\n"
        "User: Read two integers a and b from stdin (space-separated on one line) "
        "and print their sum.\n"
        "Assistant: Step 1: read one line, split on whitespace, parse two ints. "
        "Step 2: print their sum. Let me verify with a sample input before "
        "finalizing.\n"
        "<tool_call>code_interpreter(code=\"a, b = map(int, input().split())\\n"
        "print(a + b)\", stdin=\"3 5\")</tool_call>\n"
        "Tool result: 8\n"
        "Assistant: Verified -- 3 + 5 = 8 is correct. This is my final program.\n"
        "<answer>a, b = map(int, input().split())\nprint(a + b)</answer>"
)

FUNCTIONAL_SYSTEM_PROMPT_SUFFIX = (
    "\n\nFor programming problems given as a function signature (a `class Solution` "
        "starter), your solution is graded by importing the LAST code you pass to "
        "code_interpreter and CALLING the required method directly with the test "
        "arguments -- code you only write in text but never run does not count, and "
        "nothing is read from stdin. Requirements: (a) define `class Solution` with the "
        "method name and parameter order EXACTLY as given in the starter code, (b) "
        "RETURN the answer from that method (do not print it), (c) make sure that same "
        "code_interpreter call contains the full class definition. Break the problem "
        "into steps, and before submitting, VERIFY your solution by calling it on the "
        "example inputs inside the same code_interpreter call and printing the result "
        "(extra prints are ignored at grading time)."
    + "\n\nExample:\n"
        "User: Given a list of integers nums and an integer target, return the indices "
        "of the two numbers that add up to target.\n"
        "```python\nclass Solution:\n    def twoSum(self, nums: List[int], target: int) -> List[int]:\n"
        "        \n```\n"
        "Assistant: Step 1: one pass, keep a value -> index map. Step 2: for each value, "
        "check whether target - value was already seen. Let me verify on the example "
        "before finalizing.\n"
        '<tool_call>code_interpreter(code="class Solution:\\n    def twoSum(self, nums: '
        "List[int], target: int) -> List[int]:\\n        seen = {}\\n        for i, v in "
        "enumerate(nums):\\n            if target - v in seen:\\n                return "
        "[seen[target - v], i]\\n            seen[v] = i\\n        return []\\n\\n"
        'print(Solution().twoSum([2, 7, 11, 15], 9))")</tool_call>\n'
        "Tool result: [0, 1]\n"
        "Assistant: Verified -- indices [0, 1] give 2 + 7 = 9. This is my final solution.\n"
        "<answer>class Solution:\n    def twoSum(self, nums: List[int], target: int) -> List[int]:\n"
        "        seen = {}\n        for i, v in enumerate(nums):\n"
        "            if target - v in seen:\n                return [seen[target - v], i]\n"
        "            seen[v] = i\n        return []</answer>"
)
